---
# tasks file for ovirt-engine-devel

# setup repos

- yum_repository:
    name: ovirt-tested-master
    description: ovirt-tested-master
    baseurl: "http://plain.resources.ovirt.org/repos/ovirt/tested/master/rpm/{{ platform }}$releasever"
    gpgcheck: no


# install packages

- dnf:
    name: "{{item}}"
    state: latest
  with_items:
      - git
      - git-gui
      - java-devel
      - mailcap
      - unzip
      - maven
      - openssl
      - bind-utils
      - postgresql-server
      - postgresql-contrib
      - m2crypto                       # all=m2crypto
      - python-dateutil                # all=python-dateutil ; fc=python2-dateutil
      - python-psycopg2                # all=python-psycopg2 ; fc=python2-psycopg2
      - python-jinja2                  # all=python-jinja2 ; fc=python2-jinja2
      - libxml2-python                 # all=libxml2-python ; fc=python-libxml2, python2-libxml2
      - python-daemon                  # all=python-daemon ; fc=python2-daemon
      - python-netaddr                 # all=python-netaddr ; fc=python2-netaddr
      - python-cheetah                 # all=python-cheetah ; fc=python2-cheetah
      - libselinux-python              # all=libselinux-python ; fc=python2-libselinux
   # AppServer
      - ovirt-engine-wildfly
      - ovirt-engine-wildfly-overlay
   # otopi
      - otopi-java                     # all=otopi-java
      - otopi-common                   # all=otopi-common
      - python2-otopi                  # all=otopi, python-otopi, python2-otopi
   # oVirt packages
      - ovirt-ansible-roles            # all=ovirt-ansible-roles
      - python2-ovirt-host-deploy      # all=ovirt-host-deploy, python-ovirt-host-deploy, python2-ovirt-host-deploy
      - python2-ovirt-setup-lib        # all=python2-ovirt-setup-lib
      - ovirt-js-dependencies
      - ovirt-engine-metrics
   ## optionals
      - python-pyflakes                # all=pyflakes, python-pyflakes ; fc=python2-pyflakes
      - python-pep8                    # all=python-pep8 ; fc=python2-pep8
      - python2-isort                  # all=python-isort, python2-isort
      - python-docker-py               # all=python-docker-py ; fc=python2-docker-py ; el=docker-python


# checkout code

- name: checkout engine
  become: true
  become_user: "{{ username }}"
  git:
    repo: 'https://gerrit.ovirt.org/ovirt-engine'
    dest: "{{ project_dir }}/ovirt-engine"


# configure database

- name: postgres initdb
  command: /usr/bin/postgresql-setup initdb creates=/var/lib/pgsql/data/postgresql.conf

- name: enable postgresql service
  service:
    name: postgresql
    enabled: yes
    state: started


# engine has a few postgres requirements

- lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                 regexp='host\s+all\s+all\s+127.0.0.1/32\s+.*'
                 line='host all all 127.0.0.1/32 password'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                 regexp='host\s+all\s+all\s+::1/128\s+.*'
                 line='host all all ::1/128 password'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                 regexp='max_connections'
                 line='max_connections = 150'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                 regexp='autovacuum_vacuum_scale_factor'
                 line='autovacuum_vacuum_scale_factor = 0.01'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                 regexp='autovacuum_analyze_scale_factor'
                 line='autovacuum_analyze_scale_factor = 0.075'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                 regexp='autovacuum_max_workers'
                 line='autovacuum_max_workers = 6'
  notify: restart postgresql

- lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
                 regexp='work_mem'
                 line='work_mem = 8192'
  notify: restart postgresql

# create engine user

- name: create postgres engine user
  become: true
  become_user: postgres
  postgresql_user:
    name: engine
    password: engine


# create engine database

- name: Create engine database
  become: true
  become_user: postgres
  postgresql_db:
    name: engine
    template: template0
    owner: engine
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
  notify: restart postgresql

- name: drop v1 uuid function
  become: true
  become_user: postgres
  command: psql engine -c 'DROP FUNCTION IF EXISTS uuid_generate_v1();'
  notify: restart postgresql
  failed_when: false

- name: create uuid-ossp function
  become: true
  become_user: postgres
  command: psql engine -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
  notify: restart postgresql
...
